apiVersion: v1
kind: Service
metadata:
  name: zevrant-notification-service
spec:
  ports:
    - port: 443
      targetPort: 9008
  selector:
    app: zevrant-notification-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zevrant-notification-service-deployment
  labels:
    app: zevrant-notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zevrant-notification-service
  template:
    metadata:
      labels:
        app: zevrant-notification-service
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        architecture: amd64
      containers:
        - name: zevrant-notification-service
          image: docker.io/zevrant/zevrant-notification-service:$VERSION
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: zevrant-notification-service-aws
                  key: username
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: zevrant-notification-service-aws
                  key: password
            - name: ENVIRONMENT
              value: $ENVIRONMENT
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 9008
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /zevrant-notification-service/actuator/health
              port: 9008
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /zevrant-notification-service/actuator/health
              port: 9008
            initialDelaySeconds: 60
          resources:
            requests:
              memory: 2Gi
              cpu: 250m
            limits:
              memory: 4Gi
              cpu: 500m
