
spring:
  webflux:
    base-path: /${spring.application.name}
  profiles:
    active: local
  application:
    name: zevrant-notification-service
  main:
    allow-bean-definition-overriding: true
  aop:
    proxy-target-class: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://localhost:9011/auth/realms/zevrant-services-local
        registration:
          keycloak:
            client-id: ${zevrant.services.oauth.clientId}
            client-secret: ${zevrant.services.oauth.clientSecret}
      resourceserver:
        jwt:
          issuer-uri: ${spring.security.oauth2.client.provider.keycloak.issuer-uri}

server:
  ssl:
    key-store: /storage/keys/zevrant-services.p12
    key-store-password: ${password}
  port: 9008

zevrant:
  unsecured:
    endpoints: /actuator/health,/actuator/info/,/actuator/prometheus,/webhooks/**
  services:
    oauth:
      clientId: ${notifications.oauth.clientId}
      clientSecret: ${notifications.oauth.clientSecret}
    email:
      returnAddress: zevrant@zevrant-services.com
      addressees: gerethd@gmail.com #comma delimited list
    discord:
      url: ${notifications.discord.url}
  encrypted:
    properties: notifications/oauth/clientId,notifications/oauth/clientSecret

context:
  initializer:
    classes: com.zevrant.services.zevrantsecuritycommon.services.EncryptedPropertyContextInitializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    ldap:
      enabled: false


logging:
  level:
    root: INFO
